[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bpmn_assistant"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["bpmn_assistant"]