name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install `uv`
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies
      run: |
        uv sync
        uv add pytest

    - name: Install package
      run: uv pip install -e .

    - name: Test with pytest
      run: |
        uv run pytest

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create .env file from example
      run: cp src/bpmn_assistant/.env.example src/bpmn_assistant/.env

    - name: Build and start containers
      run: |
        docker compose build
        docker compose up -d

    - name: Verify containers are running
      run: |
        # Check if all containers started successfully
        if [ $(docker compose ps -q --status running | wc -l) -lt 3 ]; then
          echo "Not all containers are running"
          docker compose logs
          exit 1
        fi

    - name: Clean up
      run: docker compose down